### ISSUE TITLE
Plotly is not loaded with version 0.1.5...

### ISSUE THREAD

**Issue by petasis** [wildfish/django-dashboards#14]
Hi all,

I have just upgraded from version 0.1.4 to 0.1.5, and now plots are not shown.

There is an error in browser console: `Uncaught ReferenceError: Plotly is not defined`.

The problem seems to be that `plotly.min.js` in no longer included in the HTML page.

**Comment by jamesoutterside** [comment]
Hi @petasis 

0.1.5 refactored how the media is defined on the dashboards, I suspect that's where you issue is coming from, apologies for that! 

The change was https://github.com/wildfish/django-dashboards/commit/dd7c7e9a7ef8cf8db628d368824b8955a7ed4a01 which is to allow us to support custom renders.

The change was included on the base template, so if you are still using that, you should have no issue. Are you by any chance using a customer `dashboards.html` template or defining they dashboard in a custom view? If that is the case I'll update the docs to make that clearer. If not, could you post a snippet of your code that'd be helpful to debug. 

Thanks!

**Comment by lsmoker** [comment]
I was able to make it work 0.1.6 by adding this:
`<script src="{% static 'dashboards/vendor/js/plotly.min.js' %}"></script>`
to templates/dashboards/includes/static/js.html

Otherwise, Plotly doesn't load.

**Comment by jdwpeterson** [comment]
This issue has been resolved in the 0.1.7 release.
