### ISSUE TITLE
Add HTML in Card() heading?

### ISSUE THREAD

**Issue by petasis** [wildfish/django-dashboards#21]
Hi all,

I see that in order to enable card actions, you need a heading. However, heading seems to not accept HTML, the HTML is shown in the heading as text. 
I am trying to add a fontawesome icon, and it does not work.

Any ideas?

**Comment by OmegaDroid** [comment]
Hi @petasis,

Could you share the code you are using to set the heading text? My initial though would be that you aren't using `mark_safe` and therefore django is escaping the html but there may be something else going on in dashboards.

**Comment by petasis** [comment]
Here it is:
```
class Layout(Dashboard.Layout):
        components = ComponentLayout(
            Card(
                 Div("details",
                     css_classes={"wrapper":"table-responsive"}, grid_css_classes="span-12"),
                 heading="\uf19c <i>Activity",
                 actions = [("http://google.com", "Google")],
                 css_classes="card activity-card", grid_css_classes="span-12"
            ),
            "animals",
            grid_css_classes="span-12"
        )
```
Div does not have the `mark_safe` parameter (only Text has it).

**Comment by OmegaDroid** [comment]
I think you should be able to do 
```
from django.utils.safestring import mark_safe

class Layout(Dashboard.Layout):
        components = ComponentLayout(
            Card(
                 Div("details",
                     css_classes={"wrapper":"table-responsive"}, grid_css_classes="span-12"),
                 heading=mark_safe("\uf19c <i>Activity"),
                 actions = [("http://google.com", "Google")],
                 css_classes="card activity-card", grid_css_classes="span-12"
            ),
            "animals",
            grid_css_classes="span-12"
        )
```

The important part to note here is the heading parameter is now wrapped in `mark_safe`.

**Comment by petasis** [comment]
Thank you, it works. It was a django question it seems...
